### PR TITLE
abstract logic from evtloop

### PR DESCRIPTION
**Pull request by lolpuddle**

### CODE REVIEW

**Review by danielholmes839 — APPROVED** [review]
Looks good! I think when I start testing these I will try to switch the methods to functions. Passing the Indexer through an interface with only the required methods. This PR already makes testing easier

**Review by tav — CHANGES_REQUESTED** [review]
Great start. I like the overall intent of this PR!

I'd recommend the following changes:

1. The various methods, e.g. `ProcessAccountCreated`, take a `*processBlockState` as a parameter but then return it. Since it is a pointer value, this seems unnecessary, and should only really be done if you're planning to support `.chained().operations()`.

2. Since these methods don't actually mutate the `Indexer`, they actually make more sense as methods on `processBlockState` rather than on `Indexer`.

3. The re-assignment back to local state after calling the methods, as well as the continuation of the outer/event loops should also happen in one place at the end of the `switch`. This will allow others to rework those methods in the future without worrying about whether they've correctly updated the state re-assignment at all the call sites.

**Review by tav — CHANGES_REQUESTED** [review]
Also, I preferred the way you sort of had it before with `continueOuter` and `continueEventLoop` on the `processBlockState` instead of having them as undocumented return parameters in the methods.

**Comment by tav** [comment]
Note: you'll need to "reset" the `continueOuter` and `continueEventLoop` logic when you re-enter those loops, which I don't think you were doing before?

**Comment by lolpuddle** [comment]
> Great start. I like the overall intent of this PR!
> 
> I'd recommend the following changes:
> 
> 1. The various methods, e.g. `ProcessAccountCreated`, take a `*processBlockState` as a parameter but then return it. Since it is a pointer value, this seems unnecessary, and should only really be done if you're planning to support `.chained().operations()`.
> 2. Since these methods don't actually mutate the `Indexer`, they actually make more sense as methods on `processBlockState` rather than on `Indexer`.
> 3. The re-assignment back to local state after calling the methods, as well as the continuation of the outer/event loops should also happen in one place at the end of the `switch`. This will allow others to rework those methods in the future without worrying about whether they've correctly updated the state re-assignment at all the call sites.

**Comment by lolpuddle** [comment]
> Great start. I like the overall intent of this PR!
> 
> I'd recommend the following changes:
> 
> 1. The various methods, e.g. `ProcessAccountCreated`, take a `*processBlockState` as a parameter but then return it. Since it is a pointer value, this seems unnecessary, and should only really be done if you're planning to support `.chained().operations()`.
> 2. Since these methods don't actually mutate the `Indexer`, they actually make more sense as methods on `processBlockState` rather than on `Indexer`.
> 3. The re-assignment back to local state after calling the methods, as well as the continuation of the outer/event loops should also happen in one place at the end of the `switch`. This will allow others to rework those methods in the future without worrying about whether they've correctly updated the state re-assignment at all the call sites.

Implemented recommendations 1 & 3.

2. The methods don't mutate `Indexer` but do rely on one of Indexer's internal functions `isTracked()`

**Pull request closed without merging**
