### PR TITLE
[Rosetta] Refactor testnet integration test script

### PR DESCRIPTION
**Pull request by illia-malachyn**
How to test:
- `cd integration`
- `python3 testnet_integration_test.py --init`
- follow script instructions

### CODE REVIEW

**Comment by illia-malachyn** [comment]
I refactored only `testnet_integration_test.py`. There's also `integration_test.py` for testing against a local net and `previewnet_integration_test.py` is coming soon from Uliana's PR. They're pretty much similar, so as soon as her test is committed, I'll update both of them to match a new structure and to reuse code

**Comment by illia-malachyn** [comment]
I notice that the tests fail at some point. There's a screenshot from Flow Diver. It is not related to refactoring, rather it is related to the Crescendo upgrade.

@peterargue Do you know what is the potential reason? 

Screenshot from 2024-05-23 12-42-26

**Comment by peterargue** [comment]
As mentioned in standup, that error is most likely caused by a new feature on devnet that causes tx to fail that have not been upgraded to Cadence 1.0. I should be shut off now, so you can try again.

**Comment by illia-malachyn** [comment]
Closing in favor of https://github.com/onflow/rosetta/pull/65

**Pull request closed without merging**
